### ISSUE TITLE
Version of DB tables shall be deleted if the tables doesnot exist with uninstall action

### ISSUE THREAD

**Issue by Mai-Saad** [berlindb/core#108]
Precondition:
- Having tables in the database that are deleted with their version when uninstalling

Steps:
1- Manually Delete those tables from the database without deleting related options
2- Call the uninstall method here https://github.com/berlindb/core/blob/20d2542036fa6423c55c38af0581e8340e69f7c7/table.php#L306-L313

Expected: 
Version options related to those tables are deleted

Actual: 
Version options aren't deleted 

Impact:
With the next install, with the existing version and no tables=> those tables will never be created again unless if options were deleted manually from the database

Proposed solution: 
- Adding check here https://github.com/berlindb/core/blob/20d2542036fa6423c55c38af0581e8340e69f7c7/table.php#L376 on tables and return true if not exist but if exist then drop them and return true
- Or change the condition here https://github.com/berlindb/core/blob/20d2542036fa6423c55c38af0581e8340e69f7c7/table.php#L310 to check dropped || not exist

**Comment by JJJ** [comment]
Hey @Mai-Saad! Thank you for sharing your experience and ideas here. 👋

This is an interesting issue, because the primary function of those options is to _avoid_ checking if a table exists on every page load. When the tables are deleted without the options, how _could_ BerlinDB know?

There basically is no built-in protection against a Table/Option mismatch.

Also see #105 for some related thoughts.

Similarly to `uninstall()`,  the `create()` call inside `install()` could fail if it is called manually and the table already exists. Should `set_db_option()` only be called on _confirmed_ successful creation? I think yes, because there is no way to confirm that the tables that exist are BerlinDB's, and up-to-date if so.

Will work up a PR for this.

**Comment by JJJ** [comment]
PR merged. Issue fixed and closed! Thanks again @Mai-Saad 🙏

**Comment by Mai-Saad** [comment]
Thank you @JJJ
