### ISSUE TITLE
Maybe optimize lookups of tables in DB to stop using SHOW TABLES LIKE

### ISSUE THREAD

**Issue by Khadreal** [berlindb/core#165]
One of our customers reported a performance issue related to berlindb especially for sites with large tables. This is related to `SHOW TABLES...` query in. https://github.com/berlindb/core/blob/9c4d1fe588b4bff7b9f45091d7890bbbef9c0bc4/src/Database/Table.php#L351

The proposed solution 
Changed the query to below, we could see improved performance when we do this. we've forked the repo but before creating a PR we thought opening a ticket here to know if there are other things we aren't considering with the solution.

`SELECT table_name FROM information_schema.tables WHERE table_name = '%s' LIMIT 1`

**Comment by alexstandiford** [comment]
I'm actually going to be working with BerlinDB for a project sometime soon. While I've got it cloned I'll take a look at the PR, too. 

Thanks for sharing!

**Comment by wordpressfan** [comment]
@JJJ can we please do a release of berlindb/core with all of those merged changes? the last release date was from 2 years or more :D and we use composer to update ur package.
Thanks Boss.

**Comment by wordpressfan** [comment]
@JJJ Still can't see the release here:
https://github.com/berlindb/core/releases
Is it possible to do that release so we can get it in our composer?

**Comment by JJJ** [comment]
Could also try this:

Suppress errors, then...

```sql
SELECT 1 FROM {$this->table_name} LIMIT 0;
```

Then check `$wpdb->last_error` for errors.

**Comment by JJJ** [comment]
Reverted via https://github.com/berlindb/core/commit/6a9383ab2dad726bf2d6dbda6687da848eda22ea.

**Comment by JJJ** [comment]
Hi everyone 👋 My recommendation today is to close this issue as resolved.

The original optimization from `SHOW TABLES LIKE` to `information_schema` was reverted in `6a9383a`, and that revert shipped in `2.0.2`.

The remaining tradeoff looks acceptable:
- BerlinDB checks the stored DB version first.
- `exists()` only runs when the version is missing or outdated, during install/upgrade handling.
- `SHOW TABLES LIKE` is not the normal hot path on healthy installs.

Because of that, I would not add extra caching here, because it also adds invalidation complexity for edge cases like dropped tables, restores, and migrations, without much upside.

If we want more work in this area, I think it should be tracked in a separate enhancement issue with a narrower scope:
- trust the version option and add recovery/diagnostic tooling for missing tables, or
- experiment with a cross-database existence probe backed by integration tests.

Given the ModSecurity and SQLite concerns, leaving the current behavior alone looks like the safest outcome.

Feel free to reopen with more info, comment with new ideas, etc... ❤️
