### ISSUE TITLE
Make PSR-4 class autoloading possible

### ISSUE THREAD

**Issue by szepeviktor** [berlindb/core#2]
Please consider moving class files to `src/`
and naming class files after class names, e.g. `Schema.php`

Thank you for considering!

**Comment by alexstandiford** [comment]
With the way BerlinDB is set up, I wonder if the `database` namespace is needed at all. I think it's implied that the entire toolkit would fall under the `database` namespace, which makes `BerlinDB\Database` redundant.

If we 'nixed the `Database` namespace altogether, that would also make PSR autoloading a bit cleaner. Right now, everything but the readme and license would be under the `database` directory.

**Comment by szepeviktor** [comment]
e.e. class `Compare_Query` goes into a subdirectory `src/Queries/Compare_Query.php`

**Comment by JJJ** [comment]
The WordPress coding standards say to prefix these with `class-` but I opted not to. :)

If we are going to rename these, doing so for autoloading is a good idea.

**Comment by szepeviktor** [comment]
All right.

> The WordPress coding standards say

...nothing about autoloading :)

**Comment by alexstandiford** [comment]
Well, I'm fairly certain we _could_ set this up to use WordPress standards and set up a custom autoloader inside the plugin. It would adhere to PSR autoloading standards, but could give this plugin the best of both worlds. WordPress coding standards as well as autoloading capabilities.

The more I think about it, the more it makes sense to _keep_ the database namespace. It allows the library to expand beyond database functionality, and does a better job of future-proofing the system. (unit tests, etc).

With that, I can see three different options on how autoloading could be handled:

1. Create a `bootstrap.php` file that basically registers an autoloader for the library. Use the `file` property in the `composer.json` to autoload the `bootstrap.php` file, which will handle the autoloading.
    * What's nice about this is that we _could_ adhere to WordPress standards, but still get the benefits of an autoloader. It wouldn't be PSR4 compatible, but I'm not convinced that's a big deal. But as @jjj pointed out above, we're not adhering to WP standards with class names right now, anyway.

1. Customize the PSR4 autoloader so that `BerlinDB/Database` goes to the root directory instead of the `database` directory inside of the library. This would essentially "shift" all of the files up one directory, which puts more files in the root, and keeps everyone from needing to dig into _another_ directory_ to look at these files.
    * Composer's autoload configurations are pretty straightforward, and allow us to customize which directory correlates to which namespace. This gives us a pretty simple way to move files around without breaking the dependency for other users in the process.

1. Leave it as-is, and let Composer dictate the file structure of the library moving forward.
    * I'm not convinced this is the best method.

Personally, I'm inclined to go with option 2, at least for now. It gives us a simple way to control the file structure, and saves us the trouble of needing to debug and deal with a home-made autoloader. Why re-invent the wheel when we're not adhering to WP standards for class naming conventions, anyway?

**Comment by szepeviktor** [comment]
If we have all class files in `database` there are two ways

- keep all namespaces in 1 directory
- have subdirectories

then we can tell it to Composer

```json
{
    "autoload": {
        "classmap": ["database/"]
    }
}
```

**Comment by szepeviktor** [comment]
A WordPress plugin and a Composer packages is a strange marriage.

**Comment by szepeviktor** [comment]
> and keeps everyone from needing to dig into _another_ directory to look at these files.

Are we expecting users who are not used to have PHP code in a separate (`src/`) directory?

**Comment by alexstandiford** [comment]
Yeah, it's a little odd. That being said, this isn't a WordPress plugin. It's a _dependency_ for plugins.

> Are we expecting users who are not used to have PHP code in a separate (src/) directory??

Yeah, that's a good point. These files are usually in a sub-directory anyway. And as I think about this more, I'm becoming more inclined to go with option 3, just because I'm worried about non-composer integrations. It's generally a good idea to match expectations when doing this sort-of thing.

**Comment by alexstandiford** [comment]
PR: #6

**Comment by DrewAPicture** [comment]
@JJJ 
> The WordPress coding standards say to prefix these with class- but I opted not to. :)

Why? If the the idea is that this would be considered a dependency for WordPress plugins, seems like we'd want to be stewards of best practice in the community we're building for.

**Comment by szepeviktor** [comment]
It is clearly visible that prefixing files names with `class-` is not a "best practice".
It is a remnant of ancient PHP versions where there was no namespace and there were no PSRs.

**Comment by szepeviktor** [comment]
Please see packages in Jetpack https://github.com/Automattic/jetpack/tree/master/packages/sync/src and WC https://github.com/woocommerce/woocommerce/tree/master/src and Automattic's own https://github.com/Automattic/phpcs-neutron-standard

**Comment by DrewAPicture** [comment]
> It is clearly visible that prefixing files names with class- is not a "best practice".
> It is a remnant of ancient PHP versions where there was no namespace and there were no PSRs.

It's perfectly acceptable best practice _in the community we're building for_. We can name the files to follow some arbitrary PSR just to prove something to the wider developer community or we can dance with the what that brung us. In the end, there's no difference in what you ultimately get, just how you got there. Adhering to PSR-4 just to make a point is silly.

**Comment by szepeviktor** [comment]
> Adhering to PSR-4 just to make a point is ~silly~ pointless.

PSR-4 is straightforward

- namespace -> directories
- class name -> file name

I think there is no simpler system.

**Comment by DrewAPicture** [comment]
Please understand, I'm not arguing the merits of PSR-4 in general. I'm arguing the merits of using it _in this context_. BerlinDB is intended to be a widespread dependency in WordPress plugins in a community where PSR-4 adherence carries very little weight. 

WordPress is not represented in the PHP-FIG nor does it adhere to any PSRs, so, imho, embracing PSR-4 _just because_ an external community of developers thinks it's a good idea isn't a good enough reason, imo.

**Comment by DrewAPicture** [comment]
@szepeviktor I saw you ghost updated your quoted text with my ghost-edited reply. Love the attention to detail 😜

**Comment by szepeviktor** [comment]
> I'm arguing the merits of using it _in this context_.

I totally understand you point. Actually I agree.

Maybe Automattic has another opinion, see https://github.com/berlindb/core/issues/2#issuecomment-538295368 above

**Comment by Mte90** [comment]
maybe during hacktoberfest someone will do a pr with that implementation and we can see how works.

**Comment by szepeviktor** [comment]
Something is cooking: https://meta.trac.wordpress.org/ticket/3791#comment:24 WP.org raise max PHP version to 7.2

**Comment by alexstandiford** [comment]
So, I submitted a PR #6 to handle this a while back, but it seems like there's some difference of opinion in how this would be implemented.
