### ISSUE TITLE
This project is abandoned?

### ISSUE THREAD

**Issue by Mte90** [berlindb/core#24]
As I can see there was a high momentum after WCEU (I was there at the talk) and a lot of people was interested on getting this library.

Right now this project is not very healthy also if there is an organization, there are no maintainers so doesn't have much sense to have an organization.

Also, there is no documentation but it is suggested to reverse engineering other plugins that use it (#7).
There are also different pull requests that are stalling since months and this is not inviting getting new contributors (why I have to contribute if no one cares of what I do).

Doesn't include also a comparison with others ORM or WordPress Orm like to just understand if it is helpful.

I am just asking here to move on the project in a solid way and not just publish the code as it is that is not very helpful to change the WordPress ecosystem (instead a lot of people was thinking that this project can do that).

**Comment by binaryfire** [comment]
@Mte90 I agree it would be great to get some documentation but I seriously doubt this project has been abandoned. It's at the core of Sandhills products like Easy Digital Downloads 3.0 and Restrict Content Pro.

Right now it seems like a purely internal project for them, but hopefully we'll see some community interaction from them on here soon.

**Comment by alexstandiford** [comment]
I've been using it on personal projects as well as projects inside Sandhills. I definitely agree that it needs documentation, I just don't think anyone has made the time to actually do it yet.

I know it's not ideal, but the code is well-documented, and you can get a pretty good idea on how to use it based on the [this code](https://github.com/easydigitaldownloads/easy-digital-downloads/tree/release/3.0/includes/database) in EDD.

PS: The project is absolutely _not_ dead.

**Comment by Mte90** [comment]
I see @alexstandiford that you are doing a lot of pr to the project to handle issues and bugs but my philosophy is that if the maintainer is not following/participating to the project and there are no co-maintainers is dead (also if it is used).

How I can thrust a project to use it in other solutions if there is no support about real issues? Maybe is necessary a fork?
That's my point, I see that the project is valuable and there are patches but without any acting on them for me is like the original project is dead.

I am here to change my mind :-D

**Comment by DrewAPicture** [comment]
@Mte90 Sorry for any confusion. @alexstandiford, @JJJ, and I are all Sandhills employees and while this isn't strictly a Sandhills-owned project, we _are_ utilizing it in two of our products and it most certainly is not dead. It may not currently be under active development on the public facing end, but that's in large part due to having our hands incredibly full already :wink: 

Due to the aforementioned fact that some flavor of BerlinDB is in use in some of our products, forward momentum here is assured. When and how is currently the question.

**Comment by DrewAPicture** [comment]
I have a feeling that this project will see a big boost of activity once we ship EDD 3.0, which leveraged this framework. We're going to have to overhaul our own developer documentation in the process and seeing those improvements overflow into this repository is inevitable.

**Comment by JJJ** [comment]
I strongly dislike issues like these.

I maintain dozens of open source projects here in GitHub. Many of them go through periods of non-development – sometimes long ones – because they have achieved the goals they originally set out to achieve, and nothing more is being asked of them.

The open issues and PRs in this one, have not been ignored. They have responses. They have discussion.

Code never dies.

Closing this.

**Comment by Mte90** [comment]
Hi JJJ I know that you maintain a lot of OSS projects and me too (maybe of not that size).

I got more information about the future of this project in this ticket that in the readme itself, if I am looking for updates or a roadmap on a project there are various resources but this project has only this repo.

I am not the only one that is following the project and no action in the various ticket/pr for many of us is like that the project is abandoned, usually on GitHub this is what happens when there is this situation.
Before of open this ticket I waited few days because I don't like it too.

Code never dies it is true but became obsolete or incomplete, basically not usable in most of the cases in a long term. So I was asking just to understand if there are plans and there are, it is not just code placed on GitHub as I was thinking.

Just a conclusion to let you know that a lot of people in the community wait a new solution to replace the various ORM or custom solution to db and this stalling is creating a lot of doubt, with the risk of https://xkcd.com/927/

**Comment by JJJ** [comment]
@Mte90 i get it. I’m sorry. I hastily closed this issue without much of an explanation.

In my 15 years of contributing to WordPress, the “is this thing dead?” topics and issues and threads are the worst of my times, because the _only_ thing everyone hopes for is Life in their code.

That comes from people contributing.

(Every issue and PR from @alexstandiford had me excited to look into it, but I’m also not going to make empty promises of “looking into it” if I know I can’t prioritize that.)

If code looks inactive but is actually useful, again, the only thing you can do to help it is use it and improve it.

Asking other people if they see the what you see builds a mob, and when that question is one of insecurity, it only builds more insecurity.

I’m sorry, again, for being short earlier. I was frustrated, and I let it show through here, and I shouldn’t have. 🙏
