### ISSUE TITLE
Examples on how to use it

### ISSUE THREAD

**Issue by Mte90** [berlindb/core#7]
Right now is required to study the code of the ohter plugins that use it.
It will be helpful a bit of examples or docs to evaluate it in future projects :-)

**Comment by szepeviktor** [comment]
> to study the code

On my Twitter feed I always encourage developers to do just that.

It gives you deep understanding and complete control.

Maybe not everyone is a _toolmaker_ type.

**Comment by Mte90** [comment]
And usually is a good way... when you have time to dedicate on that.

Right now I am evaluating the project and right now is not so inviting to give more time on investigate it.

**Comment by Mte90** [comment]
I see an example of schema at https://github.com/sugarcalendar/sugar-event-calendar-lite/blob/master/sugar-event-calendar/includes/classes/database/events/class-schema.php

Looking at https://github.com/sugarcalendar/sugar-event-calendar-lite/blob/master/sugar-event-calendar/includes/classes/database/events/class-table-events.php seems that we still need to do the query for create the table and is not automatically generated.

**Comment by VesterDe** [comment]
I'm excited about the possibility of BerlinDB, but I don't think the average Joe has the time to go look at how several other plugins implement it in order to learn how to use it.

There have been a plethora of solutions to the ever-stressful WordPress ORM/Model question that grew stale and stopped adding new features, i.e.:

https://github.com/hanamura/wp-model
https://github.com/anthonybudd/WP_Model
https://github.com/brandonwamboldt/wp-orm

(off the top of my head, many more are out there, mostly archived)

If BerlinDB is being used in production for several high-profile plugins that's great. But I feel WordPress really **_needs_** a solution for this that is not obscured behind a lack of documentation and tutorials. It seems like there's a good chance this project will continue to exit and grow, and I'm just throwing my 2 cents in to say: please take this seriously, and give the community a tool it desperately needs.

I forever dream of using tools as powerful as Eloquent and Doctrine for enterprise WordPress solutions, without actually needing to bring half of Symfony  and/or Laravel into the mix.

I'm sure WordPress can (should?) roll a powerful ORM-ish layer, and I'm willing to bet a lot of developers' lives would improve with one.

Thank you for coming to my TED talk.

**Comment by szepeviktor** [comment]
Please cross out ~~WP_Model~~ as it is very poorly written and incomplete.

**Comment by VesterDe** [comment]
I'm not saying any of the things on my list are good or bad, they're just _attempts_.

I added "that are of varying quality" before it. I still think it belongs on the list.

**Comment by alexstandiford** [comment]
Hey everyone,

I made a WordPress example plugin. This plugin provides some bare-minimum code to get a table registered with BerlinDB, and should help you get started.

https://www.github.com/berlindb/wordpress-example

We're still working on the documentation, but in the meantime we will work on that in #23. You can also post a question in the discussions section of the repository: https://github.com/berlindb/core/discussions

I think this means we can safely close this issue now. Thanks everyone for chiming in!
