### ISSUE TITLE
Remove applying stripslashes on string content columns before saving them

### ISSUE THREAD

**Issue by engahmeds3ed** [berlindb/core#97]
## Introduction

Here
https://github.com/berlindb/core/blob/master/query.php#L2057

We are checking if the type of the value being saved is a string then we strip slashes from it.

## The problem

This may be a problem when the content contains a backslash like in the following CSS file:

https://themes.trac.wordpress.org/browser/storefront/3.5.1/assets/css/base/icons.css
as mentioned in this issue: https://github.com/woocommerce/storefront/issues/1662

so we need to save the content as is without any stripping.

## Proposed solution

We don't think that we need this `stripslashes` at all and we need to save into the DB the content as is without any restriction.
and if this was added here because of old versions of WP we may check the version of WP being used and apply this `stripslashes` on those old versions only.

**Comment by ashleyfae** [comment]
I also had this problem in RCP when trying to save a namespaced class (which contained a backslash).

Although I appreciate BerlinDB is trying to fix a potential gotcha with stripslashes, I personally feel like it should be up to the person _implementing_ BerlinDB to do that themselves prior to the database layer. (In their own sanitization.)

**Comment by JJJ** [comment]
> I personally feel like it should be up to the person _implementing_ BerlinDB to do that themselves prior to the database layer. (In their own sanitization.)

You are right, and I do agree with you.

> if this was added here because of old versions of WP we may check the version of WP being used and apply this stripslashes on those old versions only.

Unfortunately it's all WordPress versions, due to PHP versions older than 5.4 and magic quotes.

Relevant reading to explain my paranoia regarding removing it:
* [`wp_magic_quotes()`](https://developer.wordpress.org/reference/functions/wp_magic_quotes/)
* [`add_magic_quotes()`](https://developer.wordpress.org/reference/functions/add_magic_quotes/)
* https://core.trac.wordpress.org/ticket/48605
* https://core.trac.wordpress.org/ticket/47783
* https://core.trac.wordpress.org/ticket/40716
* https://core.trac.wordpress.org/ticket/34297
* https://core.trac.wordpress.org/ticket/22325
* https://core.trac.wordpress.org/ticket/18322 ❤️

----

Will put together a pull request so everyone can test. 👍
